### ISSUE TITLE
Update the dependencies

### ISSUE THREAD

**Issue by stanislav-tkach** [vasi/positioned-io#17]
Could you please update `byteorder` and `winapi` dependencies and publish a new version?

**Comment by niklasf** [comment]
@vasi has given me access to the repository in order to help with maintenance. However I can't reach them, and I don't have access to the crate on crates.io, so a while back I decided to make a [preview branch](https://github.com/vasi/positioned-io/tree/positioned-io-preview) and publish to https://crates.io/crates/positioned-io-preview.

The dependencies of that crate are up to date.

**Comment by stanislav-tkach** [comment]
@niklasf Thank you for the quick response! I think that `positioned-io-preview` is a somewhat confusing name if this crate potentially can never be updated.

**Comment by vasi** [comment]
Hey, sorry about that! I added niklasf to a team that should have release rights on crates.io. Please let me know if it works!

**Comment by niklasf** [comment]
Hi, thanks, it works. I now published the latest "preview" release as an official release.
